#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#
setopt NO_NOMATCH

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/.zprofile

# Customize to your needs...

# Fix git update
zstyle ':prezto:module:git:info' verbose yes

function gi() { curl -L -s https://www.gitignore.io/api/$@ ;}
